name: Docker

on:
  workflow_call:
    inputs:
      build_tag:
        description: "Optional tag for Docker build"
        required: false
        type: string
  schedule:
    - cron: '18 18 * * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # … rest of your Docker build steps …
