name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

  # A → B
  docker-publish:
    needs: greet
    uses: ./.github/workflows/docker-publish.yml
    with:
      build_tag: "manual-trigger"

  # A → C
  new-workflow:
    needs: greet
    uses: ./.github/workflows/new.yaml
    with:
      example_input: "manual-trigger"

  # B → D
  testing:
    needs: docker-publish
    uses: ./.github/workflows/testing.yaml
    with:
      name: "manual-trigger"

  # A → Jira (extra workflow)
  jira:
    needs: greet
    uses: ./.github/workflows/jira.yml
    with:
      build_tag: "manual-trigger"
