name: New Workflow

on:
  workflow_call:
    inputs:
      example_input:
        description: "An example input"
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello from new workflow with input ${{ inputs.example_input }}"
