name: Test Workflow

on:
  workflow_call:
    inputs:
      name:
        description: "Person to greet"
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
